title: Dr. Marissa Walker
#author: Marissa Walker
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Postdoctoral researcher
  California State University Fullerton

# social links
#twitter_username: your-twitter-handle
#github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
